### ISSUE TITLE
We are a team of 2

### ISSUE THREAD

**Issue by emiliazm** [emiliazm/webapp#21]
# We are a team of two

@emiliazm @aliveGUY 
https://github.com/emiliazm/webapp/projects/2

**Comment by brytebee** [comment]
Hi, @emiliazm & @aliveGUY👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- The number of team members is specified.✔️
- A link to the project is provided.✔️
- The Kanban board is set up.✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️

- Kindly assign every card on the Kanban board to a member of the team. This includes the cards for group projects. They could be assigned to a single member of the team or both of you. This is to ensure that throughout the project development, it is clear to every member of the team what is their roles and duties.
![image](https://user-images.githubusercontent.com/27709832/168644475-8453adf3-08cf-4ce1-addc-0a21b510945d.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emiliazm** [comment]
Hello @brytebee !
Thank you for your comments!
### These are the changes that we implemented:
- Assign every card on the Kanban board to a member of the team.

**Comment by Kingstalux** [comment]
Hi @emiliazm and @aliveGUY,
# Status: Approved ✔️ ✔️ ✔️ 
 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/168659702-5e570601-4cbf-4dfb-bea2-c5b2a59f3fde.gif)

Good job making sure that all cards have assignees 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
